app/models.py
from .import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Blog(db.Model):
    '''
    Blog class to define the blog objects
    '''
    __tablename__ = 'blogs'
    id = db.Column(db.Integer, primary_key=True)
    blog = db.Column(db.String)
    submitted_by = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
  
    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blogs(cls, id):
        blogs = Blog.query.filter_by(blog_id=id).all()
        return blogs 

class Quote:
    '''
    Quotes class to define random quote objects from the API
    '''

    def __init__(self,id,author,quote):
        self.id =id
        self.author = author
        self.quote = quote
        
class Review(db.Model):
    '''
    review class to allow users to comment on a blog post
    '''
    __tablename__ = 'reviews'
    id = db.Column(db.Integer, primary_key=True)
    submitted_by = db.Column(db.String)
    review = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_review(self):
        db.session.add(self)
        db.session.commit()
    
    @classmethod
    def get_reviews(cls,id): 
       reviews = Review.query.filter_by(id = id).all()
       return reviews 


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    email = db.Column(db.String(255), unique=True, index=True)
    
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    reviews = db.relationship('Review',backref = 'user',lazy = "dynamic")
    blogs = db.relationship('Blog',backref = 'author',lazy = True)
  

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


    def __repr__(self):
        return f'User {self.username}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField,SelectField
from wtforms.validators import Required

class ReviewForm(FlaskForm):

    title  = StringField('Review title',validators=[Required()])
    review = TextAreaField('Blog Review', validators=[Required()])
    submit = SubmitField('submit')

class UpdateBlog(FlaskForm):
    blog = TextAreaField('Edit your blog here', validators = [Required ()])
    submit = SubmitField('Submit')

class BlogForm(FlaskForm):
    title = StringField("Blog Title",validators=[Required()])
    blog = TextAreaField('Write your blog post here')
    submitted_by = TextAreaField('Write your name here')
    submit = SubmitField('Submit')
    
class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
# from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager .session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
   app = Flask(__name__)

   # Creating the app configurations
   app.config.from_object(config_options[config_name])

   # Initializing flask extensions 
   bootstrap.init_app(app)
   db.init_app(app)
   login_manager.init_app(app)


   # Registering the blueprint
   from .main import main as main_blueprint
   app.register_blueprint(main_blueprint)

   from .auth import auth as auth_blueprint
   app.register_blueprint(auth_blueprint,url_prefix = '/auth')
   
   from .requests import configure_request
   configure_request(app)
   
   # Configure UploadSet
   configure_uploads(app,photos)

   mail.init_app(app)

   return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import BlogForm,UpdateBlog,ReviewForm,UpdateProfile
from ..import db,photos
from ..models import User,Blog,Quote,Review
from flask_login import login_required,current_user
from ..requests import get_quote
import markdown2
# import requests
# Review =reviews.Review 

@main.route("/")
def index():
    """
    View root page function that return the index page and its data
    """
    blogs = Blog.query.all()
    
    show_quote=get_quote()
    quote=show_quote["quote"]
    quote_author=show_quote["author"]
    title = "Home - Welcome to Blogger"
    return render_template('index.html',title=title, quote=quote,quote_author=quote_author,blogs = blogs)




@main.route("/details/<int:id>", methods=['GET', 'POST'])
@login_required
def details(id):

    reviews = Review.query.all()
    form = ReviewForm()
    if form.validate_on_submit():
        title = form.title.data
        review= form.review.data
        

        # Updated blog instance
        new_review = Review()
        new_review.title = title
        new_review.blog = review
        new_review.submit=submit
        # new_blog.author=current_user

        new_review.save_review()

        return redirect(url_for('main.details', id = id))
   
    blog=Blog.query.get_or_404(id)
    return render_template("new_review.html", blog=blog, form = form, reviews = reviews)


@main.route("/blog",methods=['GET','POST'])
@login_required
def blog():
    form = BlogForm()
    if form.validate_on_submit():
        title = form.title.data
        blog_post = form.blog.data
        submitted_by=form.submitted_by.data

        # Updated blog instance
        new_blog = Blog()
        new_blog.title = title
        new_blog.blog = blog_post
        new_blog.submitted_by=submitted_by
        new_blog.author=current_user

        # new_pitch = Pitch(pitch = pitch)

        # save pitch method
        new_blog.save_blog()

        return redirect(url_for('main.index'))

    title="Post your entry"
    return render_template('blog.html',title=title,form=form)


@main.route('/quote/<int:quote>')
def quotes(quote):

    '''
    View quotes page function that returns the quote details page and its data
    '''
    quote = get_quotes(quote)
    title = f'{quote.quote}'

    return render_template('quote.html',title = title,quote = quote)  


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

# @main.route('/review/<int:id>')
# def single_review(id):
#     review=Review.query.get(id)
#     if review is None:
#         abort(404)
#     format_review = markdown2.markdown(review.movie_review,extras=["code-friendly", "fenced-code-blocks"])
#     return render_template('review.html',review = review,format_review=format_review)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/blog.html
{% extends 'base.html'%}
{%import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro%}
<!-- Content block -->
{% block content %}
{{ wtf.quick_form(form) }}

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{%extends 'base.html'%}
{%import 'macros.html' as macro%}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to Blogger </title>
       
        {% endif %}
    </head>
    <style>
            body{
                background-image: url("https://images.pexels.com/photos/2204440/pexels-photo-2204440.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940");
                background-repeat: no-repeat;
                background-size: cover;
                background-position: 100%;
            }
        </style>
    <body>
        <div class="container">
             <h2 class=well style="background-color: blanchedalmond; color: black">
                    {{quote}}
                    {{quote_author}}
             </h2>
        <h1 class="jumbotron"><em>Welcome to BLOGGER! The Number One Site For Sharing Your Thoughts And Opinions With The World.</em></h1>
        
        <div class="row">
             {% for blog in blogs %}
            <div class="col-md-4">
                <div class=well style="background-color:black;
                color: white">
             
            <em><a href="/details/{{blog.id}}">{{blog.blog}}</a> <h2>{{blog.blog}}</em> </h2>
             <em><h2>{{blog.submitted_by}}</h2></em>
             <em><h2>{{blog.posted.strftime("%Y-%m-%d")}}</h2></em>
        
         </div>
     </div>
    
     {% endfor %}
        </div>
       
        
       
     </body>
 
     {% endblock %}
        </div>
       

app/templates/macros.html
{% macro displayQuoteList(quote_list) %}

    {% for quote in quote_list %}
    <li>{{ quote.id}}</li>
        <li>{{ quote.quote}}</li>
        <li>{{ quote.author}}</li>
    {% endfor %}
{% endmacro %}

{% macro displayBlogList(blog_list) %}
{% for blog in blog_list %}
<li>{{ blog.id}}</li>
<li>{{ blog.blog}}</li>
<li>{{ blog.submitted_by}}</li>
<li>{{blog.posted}}</li>
{% endfor %}
{% endmacro %}

{% macro displayReviews(review_list) %}
    {% for review in review_list %}
    <li>{{review.title}}</li>
   <li>{{review.review}}</li>
    {%endfor%}
    {%endmacro%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Blog </a>
            <a href="{{url_for('main.blog')}}">Enter Blog Post</a>
<a class="btn btn-outline-info" href="{{url_for('auth.login')}}" >Log In</a>
           <a class="btn btn-outline-info" href="{{url_for('auth.register')}}">Sign In</a>        

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                
                
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
              </ul>
        </div>

    </div>
</div>

app/templates/new_review.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
{{ wtf.quick_form(form) }}
<div class="row">
     
       <div class="col-md-4">
           <div class=well style="background-color:black;
           color: white">
        
       <em><a href="/details/{{blog.id}}">{{blog.blog}}</a> <h2>{{blog.blog}}</em> </h2>
        <em><h2>{{blog.submitted_by}}</h2></em>
        <em><h2>{{blog.posted.strftime("%Y-%m-%d")}}</h2></em>
   
    </div>
</div>
{% for review in reviews %}

    {{review.}}
{%  endfor %}

   </div>
{% endblock %}
            

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}

    {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/quote.html
{% extends 'base.html'%}
<!-- Content block -->
{% block content %}
<div class="container">

    
    <div class="row">
        <div ({quote.id})>
        </div>

        <div>
            <h3>{{ quote.quote }}</h3>

            <p class="overview"> {{ quote.author}}</p>
           


        </div>
    </div>

</div>
{% endblock %}